version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- cmd: dotnet publish -c Release
artifacts:
- path: '\**\*.nupkg'
deploy:
- provider: Environment
  name: AriesDoc
  on:
    branch: master
