version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- cmd: dotnet publish -c Release
test_script:
- ps: ForEach ($folder in (Get-ChildItem -Path .\test\ -Directory -Filter *VIC*)) { dotnet test $folder.FullName }
artifacts:
- path: '\**\*.nupkg'
deploy:
- provider: Environment
  name: VicNuGet
  on:
    branch: master
